# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

.build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$PSQL_VERSION" --build-arg PSQL_VERSION=$PSQL_VERSION .
    - docker push "$CI_REGISTRY_IMAGE:$PSQL_VERSION"
  only:
    - master

build:11:
  extends: .build
  variables:
    PSQL_VERSION: 11

build:10:
  extends: .build
  variables:
    PSQL_VERSION: 10

build:9.5:
  extends: .build
  variables:
    PSQL_VERSION: 9.5