# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  IMAGE: "selectcode/posgres-backup"

services:
  - docker:dind

before_script:
  - docker login -u flobaader -p "$DOCKER_TOKEN"

.build:
  stage: build
  script:
    - docker build --pull -t "$IMAGE:$PSQL_VERSION" --build-arg PSQL_VERSION=$PSQL_VERSION .
    - docker push "$IMAGE:$PSQL_VERSION"
  only:
    - master

build:11:
  extends: .build
  variables:
    PSQL_VERSION: '11'

build:10:
  extends: .build
  variables:
    PSQL_VERSION: '10'

build:9.5:
  extends: .build
  variables:
    PSQL_VERSION: '9.5'
