# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:11:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:11" --build-arg PSQL_VERSION=11 .
    - docker push "$CI_REGISTRY_IMAGE:11"
  only:
    - master

build:10:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:10" --build-arg PSQL_VERSION=10 .
    - docker push "$CI_REGISTRY_IMAGE:10"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
